apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5  
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range .Values.envs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- if .Values.postgres }}
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef: 
                    name: {{ .Values.postgres.secretfile }}
                    key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: 
                    name: {{ .Values.postgres.secretfile }}
                    key: password
            - name: POSTGRES_SERVICE
              value: {{ .Values.postgres.service | quote }}
            - name: POSTGRES_DBNAME
              value: {{ .Values.postgres.dbname | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}        
          {{- end }}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
