{{- if .Values.sealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "mychart.fullname" . }}-sealedsecret  
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, post-delete
    "helm.sh/hook-weight": "-1"  
spec:
  encryptedData:
    {{- range .Values.sealedSecrets }}
    {{ .key }}: {{ .value }}
    {{- end }}     
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ include "mychart.fullname" . }}-sealedsecret  
      namespace: {{ .Release.Namespace }}
{{- end }}      